# Generated by Django 6.0.6 on 2026-07-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('LANDSCAPE', 'Landscapes'), ('PORTRAIT', 'Portraits'), ('ARCHITECTURAL', 'Architectural')], default='LANDSCAPE', max_length=20),
        ),
    ]
